import { mkdir, writeFile } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

// Downloads the Latin woff2 files for our two families from Google and writes
// them + local @font-face rules into public/fonts/. Run once (or when weights
// change); the files are then committed and served from our own origin.

const __dirname = dirname(fileURLToPath(import.meta.url))
const outDir = resolve(__dirname, '../public/fonts')
await mkdir(outDir, { recursive: true })

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
const cssUrl =
  'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;800&family=Plus+Jakarta+Sans:wght@400;500;700&display=swap'

const css = await (await fetch(cssUrl, { headers: { 'User-Agent': UA } })).text()

const short = (fam) => (fam.includes('Playfair') ? 'playfair' : 'jakarta')

// Split on the subset comments; keep only the `latin` blocks.
const faces = []
for (const chunk of css.split('/*').slice(1)) {
  const subset = chunk.match(/^\s*([a-z-]+)\s*\*\//)?.[1]
  if (subset !== 'latin') continue
  const fam = chunk.match(/font-family:\s*'([^']+)'/)?.[1]
  const style = chunk.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal'
  const weight = chunk.match(/font-weight:\s*(\d+)/)?.[1] ?? '400'
  const url = chunk.match(/url\((https:[^)]+\.woff2)\)/)?.[1]
  const range = chunk.match(/unicode-range:\s*([^;]+);/)?.[1] ?? ''
  if (!fam || !url) continue
  faces.push({ fam, style, weight, url, range })
}

let out = '/* Self-hosted Latin fonts — generated by scripts/fetch-fonts.mjs */\n'
for (const f of faces) {
  const name = `${short(f.fam)}-${f.weight}${f.style === 'italic' ? '-italic' : ''}.woff2`
  const buf = Buffer.from(await (await fetch(f.url)).arrayBuffer())
  await writeFile(resolve(outDir, name), buf)
  out +=
    `@font-face{font-family:'${f.fam}';font-style:${f.style};font-weight:${f.weight};` +
    `font-display:swap;src:url('/fonts/${name}') format('woff2');unicode-range:${f.range}}\n`
  console.log(`saved ${name.padEnd(24)} ${(buf.length / 1024).toFixed(1)}K`)
}
await writeFile(resolve(outDir, 'fonts.css'), out)
console.log(`\nwrote public/fonts/fonts.css (${faces.length} faces)`)
