import sharp from 'sharp'
import { readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

// Generates the inline placeholders that make screenshots appear instantly.
//
// The South African flag never flickers because it is drawn as SVG inside the
// HTML — no network request stands between the page arriving and the flag
// being visible. Screenshots are photographs of an app, so they can't be drawn
// as vectors, but they can get the same property: a 24px-wide copy of each one
// is small enough (~400 bytes) to embed directly in the HTML as a data URI.
//
// That postage-stamp is stretched over the full image box by CSS, which smooths
// it into a soft blur of the real screenshot — right colours, right shapes, in
// place at first paint. The full-size WebP is opaque, so when it lands it
// simply covers the blur. No empty boxes, no shimmer, nothing to hydrate.
//
// Run after scripts/optimize-screenshots.mjs; writes app/assets/lqip.ts.

const dir = new URL('../app/assets/screenshots/', import.meta.url).pathname
const out = new URL('../app/assets/lqip.ts', import.meta.url).pathname

const WIDTH = 24
const QUALITY = 45

const files = (await readdir(dir)).filter(f => f.endsWith('.webp')).sort()

let total = 0
const entries = []
for (const f of files) {
  const buf = await sharp(path.join(dir, f))
    .resize(WIDTH)
    .webp({ quality: QUALITY, effort: 6 })
    .toBuffer()
  const uri = `data:image/webp;base64,${buf.toString('base64')}`
  total += uri.length
  entries.push(`  '${f.replace(/\.webp$/, '')}': '${uri}',`)
}

const module = `// GENERATED by scripts/generate-lqip.mjs — do not edit by hand.
//
// A ${WIDTH}px-wide copy of every screenshot, inlined so it ships with the HTML
// and is on screen at first paint. CSS stretches it over the image box, which
// blurs it into a stand-in for the real screenshot until that arrives.

export const LQIP: Record<string, string> = {
${entries.join('\n')}
}
`

await writeFile(out, module)
console.log(`wrote app/assets/lqip.ts — ${files.length} placeholders, ${(total / 1024).toFixed(1)}K inline`)
